announce = false
debug = true
description = 'Starter Boilerplate by .cRiZZly#1337'
gamemode = 'Freeroam'
host = '0.0.0.0'
language = 'de'
modules = [ 'js-module', 'js-bytecode-module' ]
name = 'Starter Boilerplate by .cRiZZly#1337'
players = 1337
port = 7788
resources = [ 'Boilerplate']
website = 'Starter Boilerplate by .cRiZZly#1337'